default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: brewnit_dev

test:
  <<: *default
  database: brewnit_test

production:
  <<: *default
  database: brewnit
