# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  pushover_user: <%= ENV['PUSHOVER_USER'] %>
  pushover_token: <%= ENV['PUSHOVER_TOKEN'] %>
  pushover_group_recipe: <%= ENV['PUSHOVER_GROUP_RECIPE'] %>
  project_honeypot_key: <%= ENV['PROJECT_HONEYPOT_KEY'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  recaptcha_site_key: <%= ENV['RECAPTCHA_SITE_KEY'] %>
  recaptcha_secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
  google_maps_api_key: <%= ENV['GOOGLE_MAPS_API_KEY'] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  pushover_user: <%= ENV['PUSHOVER_USER'] %>
  pushover_token: <%= ENV['PUSHOVER_TOKEN'] %>
  pushover_group_recipe: <%= ENV['PUSHOVER_GROUP_RECIPE'] %>
  project_honeypot_key: <%= ENV['PROJECT_HONEYPOT_KEY'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  recaptcha_site_key: <%= ENV['RECAPTCHA_SITE_KEY'] %>
  recaptcha_secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
  google_maps_api_key: <%= ENV['GOOGLE_MAPS_API_KEY'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  pushover_user: <%= ENV['PUSHOVER_USER'] %>
  pushover_token: <%= ENV['PUSHOVER_TOKEN'] %>
  pushover_group_recipe: <%= ENV['PUSHOVER_GROUP_RECIPE'] %>
  project_honeypot_key: <%= ENV['PROJECT_HONEYPOT_KEY'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  recaptcha_site_key: <%= ENV['RECAPTCHA_SITE_KEY'] %>
  recaptcha_secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
  google_maps_api_key: <%= ENV['GOOGLE_MAPS_API_KEY'] %>
